"""Atualizando a parte de cursos para o total de aulas

Revision ID: b8994237b7e8
Revises: e376308ed1a7
Create Date: 2025-07-28 09:16:10.235681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8994237b7e8'
down_revision: Union[str, Sequence[str], None] = 'e376308ed1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('total_aulas', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'total_aulas')
    # ### end Alembic commands ###
